package com.k3c1.fitFood.domain.food.entity;


import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Getter
@Setter
@NoArgsConstructor
public class Meal {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "name", nullable = false)
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(name = "meal_time", nullable = false)
    private EatTime mealTime;

    @Column(name = "calories", nullable = false)
    private int calories; // Total calories for this meal

    // Constructor, getters and setters can be generated by Lombok
}